name: "School Management System App"
on:
    push:
        branches:
            - master2
    pull_request:
        branches:
            - master2

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: setup python 3.8
              uses: actions/setup-python@v1
            with:
                python-version: 3.8